In [5]:
import pandas as pd
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sshtunnel import SSHTunnelForwarder

#EDITAR AQUI PARA O CAMINHO DAS BASES DE DADOS -- ou fzr automatico
CAMINHO_BASES = 'C:/utfpr/bd2/Banco-de-Dados-2/Datasets'

################## DF 1: Beneficiários do Programa Bolsa Família por faixa de renda (PR) ##################
df_renda_1 = pd.read_csv(f'{CAMINHO_BASES}/Pessoas_PBF_Renda_ateFev2023.csv', sep=',', encoding='latin1')

# Index(['Código', 'Unidade Territorial', 'UF', 'Referência',
#        'Quantidade de pessoas em famílias  em situação de extrema pobreza beneficiárias do Programa Bolsa Família',
#        'Quantidade de pessoas em famílias  em situação de pobreza beneficiárias do Programa Bolsa Família',
#        'Quantidade de pessoas em famílias de baixa renda** beneficiárias do Programa Bolsa Família'],
#       dtype='str')

df_renda_1 = df_renda_1.drop(columns=['Código', 'UF'])
df_renda_1 = df_renda_1.rename(columns={'Referência':'Data', 'Unidade Territorial':'Municipio',
                                    'Quantidade de pessoas em famílias  em situação de extrema pobreza beneficiárias do Programa Bolsa Família':'Pessoas beneficiarias BF em extrema pobreza',
                                    'Quantidade de pessoas em famílias  em situação de pobreza beneficiárias do Programa Bolsa Família':'Pessoas beneficiarias BF em pobreza',
                                    'Quantidade de pessoas em famílias de baixa renda** beneficiárias do Programa Bolsa Família':'Pessoas beneficiarias BF em baixa renda'})

print(df_renda_1.columns)

Index(['Municipio', 'Data', 'Pessoas beneficiarias BF em extrema pobreza',
       'Pessoas beneficiarias BF em pobreza',
       'Pessoas beneficiarias BF em baixa renda'],
      dtype='str')

In [6]:
df_renda_2 = pd.read_csv(f'{CAMINHO_BASES}/Pessoas_PBF_Renda_dpsMar2023.csv', sep=',', encoding='latin1')

df_renda_2 = df_renda_2.drop(columns=['Código', 'UF'])

# Index(['Unidade Territorial', 'UF', 'Referência',
#        'Quantidade de pessoas em famílias beneficiárias do Programa Bolsa Família em situação de pobreza, segundo a faixa do Programa*',
#        'Quantidade de pessoas em famílias de baixa renda** beneficiárias do Programa Bolsa Família',
#        'Quantidade de pessoas em famílias com renda per capita mensal acima de meio salário-mínimo*** beneficiárias do Programa Bolsa Família'],
#       dtype='str')

df_renda_2 = df_renda_2.rename(columns={'Referência':'Data', 'Unidade Territorial':'Municipio',
                                    'Quantidade de pessoas em famílias beneficiárias do Programa Bolsa Família em situação de pobreza, segundo a faixa do Programa*':'Pessoas beneficiarias BF em pobreza',
                                    'Quantidade de pessoas em famílias de baixa renda** beneficiárias do Programa Bolsa Família':'Pessoas beneficiarias BF em baixa renda',
                                    'Quantidade de pessoas em famílias com renda per capita mensal acima de meio salário-mínimo*** beneficiárias do Programa Bolsa Família':'Pessoas beneficiarias BF renda per capita maior meio salario minimo'})

print(df_renda_2.columns)

Index(['Municipio', 'Data', 'Pessoas beneficiarias BF em pobreza',
       'Pessoas beneficiarias BF em baixa renda',
       'Pessoas beneficiarias BF renda per capita maior meio salario minimo'],
      dtype='str')

In [7]:
df_renda_final = pd.concat([df_renda_1, df_renda_2], ignore_index=True)
df_renda_final

# df_renda_final.to_csv(f'{CAMINHO_BASES}/Tabela_PBF_PANDAS.csv', index=False, encoding='utf-8')

,Municipio,Data,Pessoas beneficiarias BF em extrema pobreza,Pessoas beneficiarias BF em pobreza,Pessoas beneficiarias BF em baixa renda,Pessoas beneficiarias BF renda per capita maior meio salario minimo
0,ABATIÁ,02/2023,589.0,583,271,NaN
1,ABATIÁ,01/2023,596.0,586,271,NaN
2,ABATIÁ,05/2022,615.0,595,162,NaN
3,ABATIÁ,09/2022,584.0,567,251,NaN
4,ABATIÁ,06/2022,597.0,602,180,NaN
...,...,...,...,...,...,...
29920,XAMBRÊ,02/2026,NaN,970,206,0.0
29921,XAMBRÊ,03/2026,NaN,980,191,0.0
29922,XAMBRÊ,04/2026,NaN,1011,223,0.0
29923,XAMBRÊ,05/2026,NaN,1045,202,0.0
29924,XAMBRÊ,06/2026,NaN,1088,201,0.0

In [27]:
import pandas as pd
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sshtunnel import SSHTunnelForwarder

#EDITAR AQUI PARA O CAMINHO DAS BASES DE DADOS -- ou fzr automatico
CAMINHO_BASES = 'C:/utfpr/bd2/Banco-de-Dados-2/Datasets'

################## DF 1: Beneficiários do Programa Bolsa Família por faixa de renda (PR) ##################
dfFem_faixaEtaria = pd.read_csv(f'{CAMINHO_BASES}/PessoasFem_PBF_faixaEtaria.csv', sep=',', encoding='latin1')

# Index(['Código', 'Unidade Territorial', 'UF', 'Referência',
#        'Quantidade de pessoas do sexo feminino com idade entre 0 e 3 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 4 e 6 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 7 e 15 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 16 e 17 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 18 e 24 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 25 e 34 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 35 e 39 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 40 e 44 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 45 e 49 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 50 e 54 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 55 e 59 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade entre 60 e 64 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único',
#        'Quantidade de pessoas do sexo feminino com idade acima de 64 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único'],
#       dtype='str')

dfFem_faixaEtaria = dfFem_faixaEtaria.rename(columns={'Referência':'Data', 'Unidade Territorial':'Municipio',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 0 e 3 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único':'Beneficiarias BF feminino 0 a 3 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 4 e 6 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único':'Beneficiarias BF feminino 4 a 6 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 7 e 15 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único':'Beneficiarias BF feminino 7 a 15 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 16 e 17 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 16 a 17 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 18 e 24 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 18 a 24 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 25 e 34 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 25 a 34 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 35 e 39 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 35 a 39 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 40 e 44 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 40 a 44 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 45 e 49 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 45 a 49 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 50 e 54 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 50 a 54 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 55 e 59 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 55 a 59 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade entre 60 e 64 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino 60 a 64 anos',
                                                    'Quantidade de pessoas do sexo feminino com idade acima de 64 anos beneficiárias do Programa Bolsa Família inscritas no Cadastro Único': 'Beneficiarias BF feminino acima de 64 anos'})

dfFem_faixaEtaria = dfFem_faixaEtaria.drop(columns=['Código', 'UF'])

df_renda = pd.concat([df_renda_1, df_renda_2], ignore_index=True)
df_teste = pd.merge(df_renda, dfFem_faixaEtaria, on=['Data', 'Municipio'], how='outer')
df_teste.to_csv(f'{CAMINHO_BASES}/Tabela_TESTEE_PANDAS.csv', index=False, encoding='utf-8')
df_teste

,Municipio,Data,Pessoas beneficiarias BF em extrema pobreza,Pessoas beneficiarias BF em pobreza,Pessoas beneficiarias BF em baixa renda,Pessoas beneficiarias BF renda per capita maior meio salario minimo,Beneficiarias BF feminino 0 a 3 anos,Beneficiarias BF feminino 4 a 6 anos,Beneficiarias BF feminino 7 a 15 anos,Beneficiarias BF feminino 16 a 17 anos,Beneficiarias BF feminino 18 a 24 anos,Beneficiarias BF feminino 25 a 34 anos,Beneficiarias BF feminino 35 a 39 anos,Beneficiarias BF feminino 40 a 44 anos,Beneficiarias BF feminino 45 a 49 anos,Beneficiarias BF feminino 50 a 54 anos,Beneficiarias BF feminino 55 a 59 anos,Beneficiarias BF feminino 60 a 64 anos,Beneficiarias BF feminino acima de 64 anos
0,ABATIÁ,01/2015,NaN,NaN,NaN,NaN,NaN,NaN,253.0,75.0,146.0,183.0,92.0,109.0,70.0,46.0,26.0,14.0,4.0
1,ADRIANÓPOLIS,01/2015,NaN,NaN,NaN,NaN,NaN,NaN,267.0,40.0,101.0,170.0,69.0,69.0,45.0,47.0,22.0,9.0,4.0
2,AGUDOS DO SUL,01/2015,NaN,NaN,NaN,NaN,NaN,NaN,267.0,55.0,135.0,196.0,85.0,70.0,52.0,26.0,23.0,14.0,5.0
3,ALMIRANTE TAMANDARÉ,01/2015,NaN,NaN,NaN,NaN,NaN,NaN,1961.0,379.0,844.0,1290.0,607.0,428.0,285.0,169.0,122.0,75.0,57.0
4,ALTAMIRA DO PARANÁ,01/2015,NaN,NaN,NaN,NaN,NaN,NaN,118.0,27.0,61.0,116.0,43.0,33.0,33.0,27.0,9.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56254,VIRMOND,12/2025,NaN,386.0,170.0,0.0,31.0,24.0,60.0,10.0,31.0,66.0,21.0,19.0,10.0,15.0,9.0,2.0,0.0
56255,VITORINO,12/2025,NaN,1135.0,224.0,0.0,92.0,66.0,166.0,22.0,82.0,174.0,48.0,36.0,31.0,33.0,16.0,9.0,2.0
56256,WENCESLAU BRAZ,12/2025,NaN,3489.0,611.0,0.0,220.0,174.0,427.0,83.0,232.0,415.0,175.0,166.0,153.0,99.0,104.0,64.0,8.0
56257,XAMBRÊ,12/2025,NaN,1000.0,195.0,0.0,73.0,61.0,119.0,15.0,77.0,108.0,58.0,47.0,36.0,28.0,29.0,7.0,3.0
56258,ÂNGULO,12/2025,NaN,311.0,97.0,0.0,14.0,22.0,51.0,10.0,15.0,41.0,13.0,25.0,8.0,5.0,10.0,10.0,1.0

In [28]:
# df_teste['Pessoas beneficiarias BF renda per capita maior meio salario minimo'] = df_teste['Pessoas beneficiarias BF renda per capita maior meio salario minimo'].fillna)
# df_teste['Pessoas beneficiarias BF renda per capita maior meio salario minimo'] = df_teste['Pessoas beneficiarias BF renda per capita maior meio salario minimo'].astype('Int64')
coluna_ignorada = ['Data', 'Municipio']

# 3. Selecionando todas as colunas menos a ignorada
colunas_para_converter = df_teste.columns.difference(coluna_ignorada)

# 4. Aplicando a conversão
df_teste[colunas_para_converter] = df_teste[colunas_para_converter].astype('Int64')
print(df_teste.dtypes)

Municipio                                                                str
Data                                                                     str
Pessoas beneficiarias BF em extrema pobreza                            Int64
Pessoas beneficiarias BF em pobreza                                    Int64
Pessoas beneficiarias BF em baixa renda                                Int64
Pessoas beneficiarias BF renda per capita maior meio salario minimo    Int64
Beneficiarias BF feminino 0 a 3 anos                                   Int64
Beneficiarias BF feminino 4 a 6 anos                                   Int64
Beneficiarias BF feminino 7 a 15 anos                                  Int64
Beneficiarias BF feminino 16 a 17 anos                                 Int64
Beneficiarias BF feminino 18 a 24 anos                                 Int64
Beneficiarias BF feminino 25 a 34 anos                                 Int64
Beneficiarias BF feminino 35 a 39 anos                                 Int64
Beneficiarias BF feminino 40 a 44 anos                                 Int64
Beneficiarias BF feminino 45 a 49 anos                                 Int64
Beneficiarias BF feminino 50 a 54 anos                                 Int64
Beneficiarias BF feminino 55 a 59 anos                                 Int64
Beneficiarias BF feminino 60 a 64 anos                                 Int64
Beneficiarias BF feminino acima de 64 anos                             Int64
dtype: object

In [23]:
df_teste

,Municipio,Data,Pessoas beneficiarias BF em extrema pobreza,Pessoas beneficiarias BF em pobreza,Pessoas beneficiarias BF em baixa renda,Pessoas beneficiarias BF renda per capita maior meio salario minimo,Beneficiarias BF feminino 0 a 3 anos,Beneficiarias BF feminino 4 a 6 anos,Beneficiarias BF feminino 7 a 15 anos,Beneficiarias BF feminino 16 a 17 anos,Beneficiarias BF feminino 18 a 24 anos,Beneficiarias BF feminino 25 a 34 anos,Beneficiarias BF feminino 35 a 39 anos,Beneficiarias BF feminino 40 a 44 anos,Beneficiarias BF feminino 45 a 49 anos,Beneficiarias BF feminino 50 a 54 anos,Beneficiarias BF feminino 55 a 59 anos,Beneficiarias BF feminino 60 a 64 anos,Beneficiarias BF feminino acima de 64 anos,_merge
0,ABATIÁ,01/2015,NaN,NaN,NaN,<NA>,NaN,NaN,253.0,75.0,146.0,183.0,92.0,109.0,70.0,46.0,26.0,14.0,4.0,right_only
1,ADRIANÓPOLIS,01/2015,NaN,NaN,NaN,<NA>,NaN,NaN,267.0,40.0,101.0,170.0,69.0,69.0,45.0,47.0,22.0,9.0,4.0,right_only
2,AGUDOS DO SUL,01/2015,NaN,NaN,NaN,<NA>,NaN,NaN,267.0,55.0,135.0,196.0,85.0,70.0,52.0,26.0,23.0,14.0,5.0,right_only
3,ALMIRANTE TAMANDARÉ,01/2015,NaN,NaN,NaN,<NA>,NaN,NaN,1961.0,379.0,844.0,1290.0,607.0,428.0,285.0,169.0,122.0,75.0,57.0,right_only
4,ALTAMIRA DO PARANÁ,01/2015,NaN,NaN,NaN,<NA>,NaN,NaN,118.0,27.0,61.0,116.0,43.0,33.0,33.0,27.0,9.0,2.0,3.0,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56254,VIRMOND,12/2025,NaN,386.0,170.0,0,31.0,24.0,60.0,10.0,31.0,66.0,21.0,19.0,10.0,15.0,9.0,2.0,0.0,both
56255,VITORINO,12/2025,NaN,1135.0,224.0,0,92.0,66.0,166.0,22.0,82.0,174.0,48.0,36.0,31.0,33.0,16.0,9.0,2.0,both
56256,WENCESLAU BRAZ,12/2025,NaN,3489.0,611.0,0,220.0,174.0,427.0,83.0,232.0,415.0,175.0,166.0,153.0,99.0,104.0,64.0,8.0,both
56257,XAMBRÊ,12/2025,NaN,1000.0,195.0,0,73.0,61.0,119.0,15.0,77.0,108.0,58.0,47.0,36.0,28.0,29.0,7.0,3.0,both
56258,ÂNGULO,12/2025,NaN,311.0,97.0,0,14.0,22.0,51.0,10.0,15.0,41.0,13.0,25.0,8.0,5.0,10.0,10.0,1.0,both